<div class="row ">
    <div class="small-12 small-centered  columns">
        <h2 class="text-center" > Listar Usuário </h2>
    </div>
</div>
<div class="small-12 small-centered  columns">
    <div class="scroll">
        <table width="100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Login</th>
                    <th>Tipo</th>
                    <th>Editar</th>
                    <th>Excluir</th>
                </tr>
            </thead>
            <?php foreach ($this->usuarios as $key => $value) { ?>
                <tr>
                    <td><?php echo $this->usuarios[$key]['idUsuario']; ?></td>
                    <td><?php echo $this->usuarios[$key]['nome']; ?></td>
                    <td><?php echo $this->usuarios[$key]['login']; ?></td>
                    <td><?php echo $this->usuarios[$key]['tp_acesso']; ?></td>
                    <td width="50px"><a href="/usuario/update/idUsuario/<?php echo $this->usuarios[$key]['idUsuario']; ?>" class="tiny button secondary">Editar</a></td>
                    <td width="50px">
                        <?php if ($this->qtdeLinhas != 1): ?> 
                            <a href="/usuario/delete/idUsuario/<?php echo $this->usuarios[$key]['idUsuario']; ?>" onclick="return confirm('Confirma a exclução do login : <?php echo $this->usuarios[$key]['login']; ?> ?');" class="tiny button alert" id="btn_usuario_excluir" >Excluir</a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php  } ?>
        </table>
    </div>
</div>
<div class="row">
    <div class="small-12   columns">
        <a id="btn_Cadastrar_usuario" href="/usuario/create" class="button">Novo</a>
    </div>
</div>


