<?php

function converteData($data) {
    if (strstr($data, "/")) {//verifica se tem a barra /
        $d = explode("/", $data); //tira a barra
        $rstData = "$d[2]-$d[1]-$d[0]"; //separa as datas $d[2] = ano $d[1] = mes etc...
        return $rstData;
    } else if (strstr($data, "-")) {
        $data = substr($data, 0, 10);
        $d = explode("-", $data);
        $rstData = "$d[2]/$d[1]/$d[0]";
        return $rstData;
    } else {
        return '';
    }
}
?>

<div class="row ">
    <div class="small-12 columns">
        <h2 class="text-center" >  Relatorio de contas a receber </h2>
    </div>
</div>
<div class="row">
    <div class="small-12 column">
        <?php if (isset($this->mensagens)) { ?>
            <div data-alert class="alert-box alert ">
                <?php echo $this->mensagens; ?>
                <a href="#" class="close">&times;</a>
            </div>
        <?php } ?>
    </div>
    <?php echo $this->form ?>
    
    
    
    
</div>
<p></p>
<div class="small-12 small-centered    columns">
    <table width="100%">
        <thead>
            <tr>
                <th>#</th>
                <th>idVenda</th>
                <th>Nome Cliente </th>
                <th>Valor</th>
                <th>Valor Pago Amortizado </th>
                <th>Restante - Troco</th>
                <th>Data de Vencimento</th>
                <th>Data de Pagamento</th>
                <th>Numero da Parcela</th>
                <th>Situacao</th>

            </tr>
        </thead>
        <?php
        foreach ($this->CR as $key => $value) {
            ?>
            <tr>
                <td><?php echo $this->CR[$key]['idContasR']; ?></td>
                <td><?php echo $this->CR[$key]['idVenda']; ?></td>
                <td><?php echo $this->CR[$key]['nome']; ?></td>
                <td><?php echo "R$" . number_format($this->CR[$key]['valor'], 2, ',', ''); ?></td>
                <td><?php echo "R$" . number_format($this->CR[$key]['valorPago'], 2, ',', ''); ?></td>
                <td><?php echo "R$" . number_format(($this->CR[$key]['valor'] - $this->CR[$key]['valorPago']), 2, ',', ''); ?></td>
                <td><?php echo converteData($this->CR[$key]['vencimento']); ?></td>
                <td><?php echo converteData($this->CR[$key]['pagamento']); ?></td>
                <td><?php echo $this->CR[$key]['numParcela']; ?></td>
                <td><?php
                    switch ($this->CR[$key]['situacao']) {
                        case 0: echo 'Aberta';
                            break;
                        case 1: echo 'Faturada';
                            break;
                        case 2: echo 'Extornada';
                            break;
                    };
                    ?>
                </td> 

            </tr>
        <?php } ?>
    </table>
</div>

