<div class="row ">
    <div class="small-12    columns">
        <h2 class="text-center" > Listar Contas a Pagar </h2>
        <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" class="custom">
            <div class="row ">
                <?php
                echo $this->form->nome;
                echo $this->form->idCompra;
                echo $this->form->situacao;
                ?>
            </div>
            <div class="row ">
                <?php
                echo $this->form->submit;
                ?>
            </div>

        </form>
    </div>
</div>


    <div class="small-12 small-centered  columns">
        <div class="scroll">
            <table width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>idCompra</th>
                        <th>Nome Fornecedor </th>
                        <th>Valor</th>
                        <th>Data de Vencimento</th>
                        <th>Data de Pagamento</th>
                        <th>Numero da Parcela</th>
                        <th>Situacao</th>
                        <th>Operação</th>
                    </tr>
                </thead>
                <?php
                foreach ($this->CP as $key => $value) {
                    
                    ?>
                    <tr>
                        <td><?php echo $this->CP[$key]['idContasP']; ?></td>
                        <td><?php echo $this->CP[$key]['idCompra']; ?></td>
                        <td><?php echo $this->CP[$key]['nome']; ?></td>
                        <td><?php echo "R$" . number_format($this->CP[$key]['valor'], 2, ',', ''); ?></td>
                        <!--<td><?php // echo $this->CP[$key]['valorPago'];     ?></td>--> 
                        <td><?php echo converteData($this->CP[$key]['vencimento']); ?></td>
                        <td><?php echo converteData($this->CP[$key]['pagamento']); ?></td>
                        <td><?php echo $this->CP[$key]['numParcela']; ?></td>
                        <td><?php
                            switch ($this->CP[$key]['situacao']) {
                                case 0: echo 'Aberta';
                                    break;
                                case 1: echo 'Faturada';
                                    break;
                                case 2: echo 'Extornada';
                                    break;
                            };
                            ?>
                        </td> 
                        <td>
                            <?php if ($this->CP[$key]['situacao'] == 0): ?> 
                                <a href="/ContasPagar/pagamento/idContasPagar/<?php echo $this->CP[$key]['idContasP']; ?>" class="tiny button ">Pagar</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>



<?php

function converteData($data) {
    if (strstr($data, "/")) {//verifica se tem a barra /
        $d = explode("/", $data); //tira a barra
        $rstData = "$d[2]-$d[1]-$d[0]"; //separa as datas $d[2] = ano $d[1] = mes etc...
        return $rstData;
    } else if (strstr($data, "-")) {
        $data = substr($data, 0, 10);
        $d = explode("-", $data);
        $rstData = "$d[2]/$d[1]/$d[0]";
        return $rstData;
    } else {
        return '';
    }
}
?>