<div class="row">
    <div class="small-12 columns text-center">
        <h2 class="text-center"> Efetuar Compra </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered  columns">
        <?php if (isset($this->mensagens)) : ?>
            <?php if ($this->erro): ?>
                <div data-alert class="alert-box alert ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php else: ?>
                <div data-alert class="alert-box success ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php endif ?>
        <?php endif ?>
        <div class="row">
            <?php
            echo $this->form->fornecedor;
            echo $this->form->dataCompra;
            echo $this->form->situacao;
            ?>
        </div>

        <form  method="<?php echo $this->formIten->getMethod() ?>" action="<?php echo $this->formIten->getAction() ?>" class="custom compra">
            <div class="row">
                <?php
                echo $this->formIten->estoque;
                echo $this->formIten->idItemCompra;
                echo $this->formIten->idCompra;
                echo $this->formIten->idProduto;
                echo $this->formIten->qtde;
                echo $this->formIten->compraPreco;
                echo $this->formIten->total;
                ?>
            </div>
            <div class="row">
                <div class="small-12 large-10 columns">
                    <?php if (isset($this->mensagem)) { ?>
                        <?php if ($this->erro) { ?>
                            <div data-alert class="alert-box alert ">
                                <?php echo $this->mensagem; ?>
                                <a href="#" class="close">&times;</a>
                            </div>
                        <?php } else { ?>
                            <div data-alert class="alert-box success ">
                                <?php echo $this->mensagem; ?>
                                <a href="#" class="close">&times;</a>
                            </div>
                        <?php } ?>
                    <?php } ?>
                </div>
                <?php
                echo $this->formIten->addIten;
                ?>
            </div>

        </form>


        <div class="row">
            <div class="small-12 small-centered  columns">
                <div class="scroll">
                    <table width="100%">
                        <thead>
                            <tr>
                                <th>Nome Produto</th>
                                <th>Preco de Compra</th>
                                <th>Quantidade</th>
                                <th>total</th>
                                <th>Editar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody> 
                            <?php
                            $total = 0;
                            $itens = $this->itens;
                            ?>
                            <?php foreach ($itens as $key => $value) {
                                ?>
                                <tr>
                                    <td><?php echo $itens[$key]['nomeProduto']; ?></td>
                                    <td ><?php echo "R$ " . number_format($itens[$key]['compraPreco'], 2 ,',',''); ?></td>
                                    <td ><?php echo $itens[$key]['qtde']; ?></td>
                                    <td ><?php echo "R$ " . number_format($itens[$key]['total'], 2 ,',',''); ?></td>
                                    <td width="50px"><a href="/compra/create/idCompra/<?php echo $itens[$key]['idCompra']; ?>/update/<?php echo $itens[$key]['idItemCompra']; ?>" class="tiny button secondary">Editar</a></td>
                                    <td width="50px"><a href="/compra/create/idCompra/<?php echo $itens[$key]['idCompra']; ?>/delete/<?php echo $itens[$key]['idItemCompra']; ?>" onclick="return confirm('Confirma a exclução do Iten ?');" class="tiny button alert" id="btn_usuario_excluir" >Excluir</a></td>
                                </tr>
                                <?php $total = $total + $itens[$key]['total']; ?>
                            <?php }
                            ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="3" > Total  </td>
                                
                                <td> <?php echo "R$ " . number_format($total, 2 ,',',''); ?>  </td>
                                <td>   </td>
                                <td>   </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <?php
            echo $this->form->Faturar;
            ?>
            <?php
            echo $this->form->button;
            ?>
        </div>

    </div>
</div>
