<div class="row">
    <div class="small-12 small-centered column">
        <div class="row">
            <div class="small-12 column">
                <h2 class="text-center"> Esse cliente ja existe venda</h2>
            </div>
        </div>
        <div class="row">
            <div class="small-6 columns">
                <a href="/venda/addvenda/idCliente/<?php echo $this->idVenda  ?>/novaVenda/N" class="button"> Nova venda  </a>
            </div>
            
            <div class="small-6 columns">
                <a href="/venda/addvenda/idCliente/<?php echo $this->idVenda  ?>/novaVenda/C" class="button right">Continuar venda existente </a>
                
            </div>
        </div>
    </div>
</div>