<div class="row">
    <div class="small-12 columns text-center">
        <h2 class="text-center"> Efetuar Venda </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered  columns">
        <?php if (isset($this->mensagens)) : ?>
            <?php if ($this->erro): ?>
                <div data-alert class="alert-box alert ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php else: ?>
                <div data-alert class="alert-box success ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php endif ?>
        <?php endif ?>

        <div class="row">

            <?php
            echo $this->form;
            ?>

        </div>
        <div class="row">
            <?php
            echo $this->formIten;
            ?>

        </div>
        <div class="row">
            <div class="small-12 small-centered      columns">
                <div class="scroll">
                    <table width="100%">
                        <thead>
                            <tr>
                                <th>Nome Produto</th>
                                <th>qtde</th>
                                <th>valor</th>
                                <th>total</th>
                                <th>Editar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody> 
                            <?php $total = 0 ?>
                            <?php foreach ($this->itens as $key => $value) {
                                ?>
                                <tr>
                                    <td><?php echo $this->itens[$key]['idProduto']; ?></td>
                                    <td><?php echo $this->itens[$key]['valor']; ?></td>
                                    <td><?php echo $this->itens[$key]['qtde']; ?></td>
                                    <td><?php echo $this->itens[$key]['total']; ?></td>
                                    <td width="50px"><a href="update/idItemVenda/<?php echo $this->itens[$key]['idItemVenda']; ?>" class="small button secondary">Editar</a></td>
                                    <td width="50px"><a href="delete/idItemVenda/<?php echo $this->itens[$key]['idItemVenda']; ?>" onclick="return confirm('Confirma a exclução do login : <?php echo $this->usuarios[$key]['login']; ?> ?');" class="small button alert" id="btn_usuario_excluir" >Excluir</a></td>
                                </tr>
                                <?php $total = $total + $this->itens[$key]['total']; ?>
                            <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="5" > Total  </td>
                                <td> <?php echo $total; ?>  </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

    </div>
</div>
