<?php

function databr($datasql) {
    if (!empty($datasql)) {
        $p_dt = explode('-', $datasql);
        $data_br = $p_dt[2] . '/' . $p_dt[1] . '/' . $p_dt[0];
        return print $data_br;
    }
}
?>

<div class="row ">
    <div class="small-12 small-centered large-12 columns">
        <h2 class="text-center" > Listar Venda </h2>        
        <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" class="custom">
            <div class="row">
                <?php
                echo $this->form->nome;
                echo $this->form->status;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->submit;
                ?>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered columns">
        <div class="scroll">
            <table width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Data Venda</th>
                        <th>total</th>
                        <th>formasPagamento</th>
                        <th>Situacao</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                <?php foreach ($this->venda as $key => $value) : ?>
                    <tr>
                        <td><?php echo $this->venda[$key]['idVenda']; ?> </td>
                        <td><?php echo $this->venda[$key]['idCliente']; ?></td>
                        <td><?php echo databr($this->venda[$key]['dataVenda']); ?></td>
                        <td><?php echo $this->venda[$key]['total']; ?></td>
                        <td><?php echo $this->venda[$key]['formasPagamento']; ?></td>
                        <td><?php
                            switch ($this->venda[$key]['situacao']) {
                                case 0:
                                    echo 'Aberta';
                                    break;
                                case 1:
                                    echo 'Cancelada';
                                    break;
                                case 2:
                                    echo 'Faturada';
                                    break;
                                case 3:
                                    echo 'Finalizada';
                                    break;
                                case 4:
                                    echo 'Extornada';
                                    break;
                                default:
                                    echo false;
                                    break;
                            };
                            ?></td>
                        <td>
                            <?php $classBotãoVenda = ($this->venda[$key]['situacao'] == 0 ) ? 'small button secondary' : 'small button secondary disabled'; ?> 
                            <a href="/venda/create/idVenda/<?php echo $this->venda[$key]['idVenda']; ?>"
                               class="<?php echo $classBotãoVenda ?>">EDITAR</a>
                        </td>
                    </tr>
                <?php endforeach; ?> <!-- End foreach -->
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered columns">
        <a id="btn_Cadastrar_usuario" href="/cliente" class="button">Novo</a>
    </div>
</div>



