<div class="row ">
    <div class="small-12 small-centered large-12 columns">
        <h2 class="text-center" > Listar Venda </h2>        
        <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" class="custom">
            <div class="row">
                <?php
                echo $this->form->nome;
                echo $this->form->status;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->submit;
                ?>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered columns">
        <div class="scroll">
            <table width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Cliente</th>
                        <th>Data Venda</th>
                        <th>total</th>
                        <th>formasPagamento</th>
                        <th>Situacao</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                <?php foreach ($this->venda as $key => $value) : ?>
                    <tr>
                        <td><?php echo $this->clientes[$key]['idVenda']; ?> </td>
                        <td><?php echo $this->clientes[$key]['idCliente']; ?></td>
                        <td><?php echo $this->clientes[$key]['dataVenda']; ?></td>
                        <td><?php echo $this->clientes[$key]['total']; ?></td>
                        <td><?php echo $this->clientes[$key]['formasPagamento']; ?></td>
                        <td><?php echo $this->clientes[$key]['situacao']; ?></td>
                        <td>
                            <a href="/venda/update/idVenda/<?php echo $this->clientes[$key]['idVenda']; ?>"
                               class="small button secondary">EDITAR</a>
                        </td>
                    </tr>
                <?php endforeach; ?> <!-- End foreach -->
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered columns">
        <a id="btn_Cadastrar_usuario" href="/cliente" class="button">Novo</a>
    </div>
</div>



