<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>CDES</title>
        <base href=" <?php echo 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['SCRIPT_NAME'] ?> " />
        <link rel="stylesheet" href="css/foundation.css" />
        <link rel="stylesheet" href="css/style.css" />
        
        <script src="js/vendor/custom.modernizr.js"></script>

    </head>
    <body>
        <nav class="top-bar">
            <ul class="title-area ">
                <!-- Title Area -->
                <li class="name">
                    <h1><a href="/">TAPEÇARIA STILLO</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li class="divider"></li>
                    <li class="has-dropdown">
                        <a href="/">Cadastro</a>
                        <ul class="dropdown">
                            <li class="divider"></li>
                            <li><a href="#">Produto</a></li>
                            <li class="divider"></li>
                            <li><a href="cliente/frm_cliente.php">Cliente</a></li>
                            <li class="divider"></li>
                            <li><a href="/usuario">Usuario</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Fornecedor</a></li>
                            <li class="divider"></li>
                            <li><a href="cidade/frm_cidade.php">Cidade</a></li>
                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li class="has-dropdown">
                        <a href="#">Movimentos</a>
                        <ul class="dropdown">
                            <li class="divider"></li>
                            <li><a href="#">Venda</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Compra</a></li>
                            <li class="divider"></li>
                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li class="has-dropdown">
                        <a href="#">Contas</a>
                        <ul class="dropdown">
                            <li class="divider"></li>
                            <li><a href="#">Pagar</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Receber</a></li>
                            <li class="divider"></li>

                        </ul>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#">Relatorios</a></li>
                    <li class="divider"></li>
                </ul>

                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="divider hide-for-small"></li>
                    <li class="divider show-for-small"></li>
                    <li class="has-form">
                        <a class="button" href="#">logoff</a>
                    </li>
                </ul>
            </section>
        </nav>

        <div id="conteudo">
            <?php echo $this->layout()->content; ?>
        </div>


        <script>
            document.write('<script src=' +
                    ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
                    '.js><\/script>')
        </script>

        <script src="js/foundation.min.js"></script>
        <script src="js/foundation/foundation.orbit.js"></script>
        <!--
        
        <script src="js/foundation/foundation.js"></script>
        
        <script src="js/foundation/foundation.alerts.js"></script>
        
        <script src="js/foundation/foundation.clearing.js"></script>
        
        <script src="js/foundation/foundation.cookie.js"></script>
        
        <script src="js/foundation/foundation.dropdown.js"></script>
        
        <script src="js/foundation/foundation.forms.js"></script>
        
        <script src="js/foundation/foundation.joyride.js"></script>
        
        <script src="js/foundation/foundation.magellan.js"></script>
        
        
        
        <script src="js/foundation/foundation.placeholder.js"></script>
        
        <script src="js/foundation/foundation.reveal.js"></script>
        
        <script src="js/foundation/foundation.section.js"></script>
        
        <script src="js/foundation/foundation.tooltips.js"></script>
      
        <script src="js/foundation/foundation.topbar.js"></script>
        -->


        <script>
            $(document).foundation();
        </script>
    </body>
</html>
