<div class="row">
    <div class="small-12 columns text-center">
        <h2> Cadastrar Produto </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered large-7 columns">
        <?php if (isset($this->mensagens)) { ?>
            <?php if ($this->erro) { ?>
                <div data-alert class="alert-box alert ">
                    <?php echo $this->mensagens; ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php } else { ?>
                <div data-alert class="alert-box success ">
                    <?php echo $this->mensagens; ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php } ?>
        <?php } ?>

        <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
            <div class="row">

                <?php
                echo $this->form->idProduto;
                ?>
                <div class="small-12 columns">
                    <?php
                    echo $this->form->status;
                    ?>
                </div>
            </div>

            <div class="row">
                <?php
                echo $this->form->descricao;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->precoCusto;
                echo $this->form->estoque;
                ?>
            </div>

            <div class="row">
                <?php
                echo $this->form->submit;
                ?>
                <?php
                echo $this->form->button;
                ?>
            </div>



    </div>
</div>
