<div class="row ">
    <div class="small-12 small-centered large-8 columns">
        <h2 class="text-center" > Listar Produto </h2>

        <form method="<?php echo $this->form->getMethod();?>" action="<?php echo $this->form->getAction(); ?>">
            <div class="row collapse">
                <?php
                echo $this->form->descricao;
               echo $this->form->submit;
                ?>
            </div>
           
        </form>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered large-8 columns">
        <div class="scroll">
            <table width="100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descricao</th>
                        <th>precoCusto</th>
                        <th>estoque</th>
                        <th>status</th>
                        <th>Tipo</th>
                        <th>Editar</th>
                    </tr>
                </thead>
                <?php foreach ($this->produtos as $key => $value) {
                    ?>
                    <tr>
                        <td><?php echo $this->produtos[$key]['idProduto']; ?></td>
                        <td><?php echo $this->produtos[$key]['descricao']; ?></td>
                        <td><?php echo $this->produtos[$key]['precoCusto']; ?></td>
                        <td><?php echo $this->produtos[$key]['estoque']; ?></td>
                        <td><?php echo $this->produtos[$key]['status']; ?></td>
                        <td width="50px"><a href="/usuario/update/idProduto/<?php echo $this->produtos[$key]['idProduto']; ?>" class="small button secondary">Editar</a></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="small-12 small-centered large-8 columns">
        <a id="btn_Cadastrar_usuario" href="/produtos/create" class="button">Novo</a>
    </div>
</div>


