<div class="row ">
    <div class="small-12    columns">
        <h2 class="text-center" > Listar Contas a receber </h2>
        <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>" class="custom">
            <div class="row ">
                <?php
                echo $this->form->nome;
                echo $this->form->idVenda;
                echo $this->form->situacao;
                ?>
            </div>
            <div class="row ">
                <?php
                echo $this->form->submit;
                ?>
            </div>

        </form>
    </div>
</div>


<div class="small-12 small-centered  columns">
    <div class="scroll">
        <table width="100%">
            <thead>
                <tr>
                    <th>#</th>
                    <th>idVenda</th>
                    <th>Nome Cliente </th>
                    <th>Valor</th>
                    <th>Valor Pago Amortizado </th>
                    <th>Restante - Troco</th>
                    <th>Data de Vencimento</th>
                    <th>Data de Pagamento</th>
                    <th>Numero da Parcela</th>
                    <th>Situacao</th>
                    <th>Operação</th>
                </tr>
            </thead>
            <?php
            foreach ($this->CR as $key => $value) {
                ?>
                <tr>
                    <td><?php echo $this->CR[$key]['idContasR']; ?></td>
                    <td><?php echo $this->CR[$key]['idVenda']; ?></td>
                    <td><?php echo $this->CR[$key]['nome']; ?></td>
                    <td><?php echo "R$" . number_format($this->CR[$key]['valor'], 2, ',', ''); ?></td>
                    <td><?php echo "R$" . number_format($this->CR[$key]['valorPago'], 2, ',', ''); ?></td>
                    <td><?php echo "R$" . number_format(($this->CR[$key]['valor'] - $this->CR[$key]['valorPago']), 2, ',', ''); ?></td>
                    <td><?php echo converteData($this->CR[$key]['vencimento']); ?></td>
                    <td><?php echo converteData($this->CR[$key]['pagamento']); ?></td>
                    <td><?php echo $this->CR[$key]['numParcela']; ?></td>
                    <td><?php
                        switch ($this->CR[$key]['situacao']) {
                            case 0: echo 'Aberta';
                                break;
                            case 1: echo 'Faturada';
                                break;
                            case 2: echo 'Extornada';
                                break;
                        };
                        ?>
                    </td> 
                    <td>
                        <?php if ($this->CR[$key]['situacao'] == 0): ?> 
                            <a href="/ContasReceber/pagamento/idContasReceber/<?php echo $this->CR[$key]['idContasR']; ?>" class="tiny button ">Pagar</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>



<?php

function converteData($data) {
    if (strstr($data, "/")) {//verifica se tem a barra /
        $d = explode("/", $data); //tira a barra
        $rstData = "$d[2]-$d[1]-$d[0]"; //separa as datas $d[2] = ano $d[1] = mes etc...
        return $rstData;
    } else if (strstr($data, "-")) {
        $data = substr($data, 0, 10);
        $d = explode("-", $data);
        $rstData = "$d[2]/$d[1]/$d[0]";
        return $rstData;
    } else {
        return '';
    }
}
?>