<div class="row">
    <div class="small-12 columns text-center">
        <h2 class="text-center"> Cadastro Cliente </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered large-7 columns">
        <?php if (isset($this->mensagens)) : ?>
            <?php if ($this->erro): ?>
                <div data-alert class="alert-box alert ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
                <?php else: ?>
                <div data-alert class="alert-box success ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php endif ?>
        <?php endif ?>

        <?php
        echo $this->form;
        ?>

    </div>
</div>
