<div class="row">
    <div class="small-12 columns text-center">
        <h2 class="text-center"> Cadastro Cliente </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered large-7 columns">
        <?php if (isset($this->mensagens)) : ?>
            <?php if ($this->erro): ?>
                <div data-alert class="alert-box alert ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php else: ?>
                <div data-alert class="alert-box success ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php endif ?>
        <?php endif ?>

        <?php
        echo $this->form;
        ?>
        <form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction() ?>">
            <div class="row">
                <?php
                echo $this->form->idCliente;
                echo $this->form->tipo;
                echo $this->form->status;
                ?>
            </div>

           <div class="row">
                <?php
                echo $this->form->nome;
                echo $this->form->CPF_CNPJ;
                ?>
            </div>

            <div class="row">
                <?php
                echo $this->form->telefone;
                echo $this->form->endereco;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->numero;
                ?>
                <?php
                echo $this->form->bairro;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->UF;
                ?>
                <?php
                echo $this->form->button;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->submit;
                ?>
                <?php
                echo $this->form->button;
                ?>
            </div>
        </form>
    </div>
</div>
