<div class="row">
    <div class="small-12 columns text-center">
        <h2> Atualizar Cliente </h2>
    </div>
</div>
<div  class="row ">
    <div class="small-12 small-centered  columns">
        <?php if (isset($this->mensagens)) { ?>
            <?php if ($this->erro) { ?>
                <div data-alert class="alert-box alert ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php } else { ?>
                <div data-alert class="alert-box success ">
                    <?php
                    foreach ($this->mensagens as $key => $value) {
                        echo $this->mensagens[$key];
                    }
                    ?>
                    <a href="#" class="close">&times;</a>
                </div>
            <?php } ?>
        <?php } ?>
        <form method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
            <div class="row">

                <?php
                echo $this->form->idCliente;
                ?>
                <div class="small-6 columns">
                    <?php
                    echo $this->form->tipo;
                    ?>
                </div>
                <div class="small-6 columns">
                    <?php
                    echo $this->form->status;
                    ?>
                </div>
            </div>

            <div class="row">
                <?php
                echo $this->form->nome;
                echo $this->form->CPF_CNPJ;
                ?>
            </div>

            <div class="row">
                <?php
                echo $this->form->telefone;
                echo $this->form->endereco;
                echo $this->form->numero;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->bairro;
                echo $this->form->UF;
                echo $this->form->cidade;
                ?>
            </div>
            <div class="row">
                <?php
                echo $this->form->submit;
                echo $this->form->button;
                ?>
            </div>
        </form>
    </div>
</div>