<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Controle de Estoque Stillo Tapeçaria</title>
        <base href="  <?php echo 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['SCRIPT_NAME'] ?> " />
        <link href="css/jquery-ui-1.9.2.custom.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/foundation.css" />
        <link rel="stylesheet" href="css/style.css" />
        <script src="js/vendor/custom.modernizr.js"></script>
    </head>
    <body>
        <nav class="top-bar">
            <ul class="title-area ">
                <!-- Title Area -->
                <li class="name">
                    <h1><a href="/">STILLO</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">

                    <li class="has-dropdown">
                        <a >Cadastro</a>
                        <ul class="dropdown">
                            <li><a href="/produtos">Produto</a></li>
                            <li><a href="/cliente">Cliente</a></li>
                            <li><a href="/usuario">Usuario</a></li>
                            <li><a href="/fornecedor">Fornecedor</a></li>
                        </ul>
                    </li>
                    <li class="has-dropdown">
                        <a >Movimentação</a>
                        <ul class="dropdown">
                            <li><a href="/venda">Venda</a></li>
                            <li><a href="">Compra</a></li>
                        </ul>
                    </li>

                    <li class="has-dropdown">
                        <a >Contas</a>
                        <ul class="dropdown">

                            <li><a >Pagar</a></li>

                            <li><a href="/ContasReceber" >Receber</a></li>


                        </ul>
                    </li>

                    <li><a >Relatorios</a></li>

                    <li>
                        <div id="nav">
                            Você está em: <a href="/" title="Home">Home</a> 
                            <?php
                            $breadCrumbs = $this->navigation()->breadcrumbs()->setLinkLast(true)->setMinDepth(0)->render();
                            echo ($breadCrumbs != "") ? "> " . $breadCrumbs : "";
                            ?>
                        </div>
                    </li>
                </ul>

                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="has-form">
                        <a class="button" href='/login/logout'>logout</a>
                    </li>
                </ul>
            </section>
        </nav>


        <div id="conteudo">
            <?php echo $this->layout()->content; ?>
        </div>


        <script>
            document.write()
        </script>
        <script src="js/vendor/jquery.js"></script>
        <script src="js/foundation.min.js"></script>
        <script src="js/script.js"></script>
        <script src="js/jquery-ui-1.9.2.custom.min.js"></script>

        <!--
        
        <script src="js/foundation/foundation.js"></script>
        
        <script src="js/foundation/foundation.alerts.js"></script>
        
        <script src="js/foundation/foundation.clearing.js"></script>
        
        <script src="js/foundation/foundation.cookie.js"></script>
        
        <script src="js/foundation/foundation.dropdown.js"></script>
        
        <script src="js/foundation/foundation.forms.js"></script>
        
        <script src="js/foundation/foundation.joyride.js"></script>
        
        <script src="js/foundation/foundation.magellan.js"></script>
        
        <script src="js/foundation/foundation.orbit.js"></script>
        
        <script src="js/foundation/foundation.placeholder.js"></script>
        
        <script src="js/foundation/foundation.reveal.js"></script>
        
        <script src="js/foundation/foundation.section.js"></script>
        
        <script src="js/foundation/foundation.tooltips.js"></script>
      
        <script src="js/foundation/foundation.topbar.js"></script>
        -->


        <script>
            $(document).foundation();
            $(function() {
                $(".datepicker").datepicker({
                    inline: true
                });
                // Hover states on the static widgets
                $("#dialog-link, #icons li").hover(
                        function() {
                            $(this).addClass("ui-state-hover");
                        },
                        function() {
                            $(this).removeClass("ui-state-hover");
                        }
                );
            });
        </script>
    </body>
</html>
